export const MESSAGE_ADD_REQUEST = 'MESSAGE_ADD_REQUEST';
export const MESSAGE_ADD_SUCCESS = 'MESSAGE_ADD_SUCCESS';
export const MESSAGE_ADD_FAIL = 'MESSAGE_ADD_FAIL';

export const MESSAGE_READ_REQUEST = 'MESSAGE_READ_REQUEST';
export const MESSAGE_READ_SUCCESS = 'MESSAGE_READ_SUCCESS';
export const MESSAGE_READ_FAIL = 'MESSAGE_READ_FAIL';

